"""Static helper data for workflow forms."""

from app.services.workflow.definition import (
    WORKFLOW_NOT_CODEABLE_BY_DATA_MANAGER,
    WORKFLOW_READY_FOR_CODING,
    WORKFLOW_SCREENING_PENDING,
)

adult = [
    "I10 - Essential Hypertension",
    "E11 - Type 2 Diabetes Mellitus",
    "E10 - Type 1 Diabetes Mellitus",
    "E66 - Obesity",
    "N18 - Chronic Kidney Disease",
    "K74 - Chronic Liver Disease",
    "J44 - Chronic Obstructive Pulmonary Disease",
    "J45 - Asthma",
    "E78 - Dyslipidemia",
    "I50 - Congestive Heart Failure",
    "I25 - Coronary Artery Disease",
    "D64 - Chronic Anaemia",
    "F03 - Dementia",
    "I25.2 - Previous Myocardial Infarction",
    "I69 - Previous Stroke/CVA",
    "C80 - Cancer (non-primary, metastasis, history)",
    "B24 - HIV/AIDS",
    "Z86.1 - Past history of tuberculosis",
    "D89 - Immunosuppression",
    "E03 - Hypothyroidism",
    "E05 - Hyperthyroidism",
    "B18 - Chronic Viral Infections (Hepatitis)",
    "I73.9 - Peripheral Vascular Disease",
    "I09 - Chronic Rheumatic Heart Disease",
    "Z98.8 - History of Major Surgery",
    "Z79.3 - Long-term use of Immunosuppressants",
]

neonate = [
    "P07 - Preterm birth",
    "P07.0, P07.1 - Low Birth Weight",
    "P05 - Intrauterine Growth Restriction",
    "P21 - Birth Asphyxia",
    "P36 - Neonatal Sepsis",
    "P23 - Neonatal Pneumonia",
    "P22 - Hyaline Membrane Disease / Respiratory Distress Syndrome",
    "P24.0 - Meconium Aspiration Syndrome",
    "P59 - Neonatal Jaundice",
    "P90 - Neonatal Convulsions",
    "P91.6 - Hypoxic Ischemic Encephalopathy",
    "P80 - Hypothermia of Newborn",
    "P70.4 - Hypoglycemia of Newborn",
    "P52 - Neonatal Hemorrhage",
    "Q20 - Q28 - Congenital Heart Disease",
    "Q00 - Q99 - Congenital Malformations",
    "Q90 - Chromosomal Abnormalities",
    "A33 - Neonatal Tetanus",
    "P37.9 - Neonatal Meningitis",
    "P77 - Necrotizing Enterocolitis",
    "P00.1 - Maternal Diabetes",
    "P00.0 - Maternal Hypertension",
    "P02.7 - Chorioamnionitis",
    "P01.5 - Twin/Multiple Gestation",
    "P35, P37 - Congenital Infections (TORCH)",
    "P58, P59 - Hyperbilirubinemia",
    "P92 - Feeding Problems of Newborn",
    "P04 - Maternal drug use affecting newborn",
]

children = [
    "J06, J20, J21 - Acute Respiratory Infections",
    "J45 - Asthma",
    "D50 - D53 - Anemia",
    "E40 - E46 - Malnutrition",
    "E66 - Obesity",
    "E10, E11 - Diabetes Mellitus (Type 1/2)",
    "G40 - Epilepsy",
    "Q20 - Q28 - Congenital Heart Disease",
    "D57 - Sickle Cell Disease",
    "D56 - Thalassemia",
    "Q90 - Down Syndrome",
    "E84 - Cystic Fibrosis",
    "N18, N04 - Renal Disease",
    "A15 - A19 - Tuberculosis",
    "B20 - B24 - HIV/AIDS",
    "D80 - D89 - Immunodeficiency",
    "I05 - I09 - Rheumatic Heart Disease",
    "G80 - Cerebral Palsy",
    "F84 - Autism Spectrum Disorders",
    "F70 - F79 - Intellectual Disability",
    "C91 - C95, C81 - C85, C00 - C80 - Cancer",
    "D57.3 - Sickle Cell Trait",
    "D56.3 - Thalassemia Trait",
    "Z98.8 - Previous Major Surgery",
    "P07 - History of Prematurity/Low Birth Weight",
    "Z28.3 - Incomplete immunization Status",
]

DATA_MANAGER_TRIAGE_ALLOWED_STATES = {
    WORKFLOW_SCREENING_PENDING,
    WORKFLOW_READY_FOR_CODING,
    WORKFLOW_NOT_CODEABLE_BY_DATA_MANAGER,
}
