"""Deterministic defaults for category-level display metadata."""

CATEGORY_DISPLAY_DEFAULTS = {
    "vainterviewdetails": {
        "display_label": "Interview Details",
        "nav_label": "Interview Details",
        "icon_name": "fa-info-circle",
        "render_mode": "table_sections",
        "show_to_coder": False,
        "show_to_reviewer": False,
        "show_to_site_pi": True,
        "always_include": False,
        "is_default_start": False,
    },
    "vademographicdetails": {
        "display_label": "Demographic / Risk Factors",
        "nav_label": "Demographic / Risk Factors",
        "icon_name": "fa-user",
        "render_mode": "table_sections",
        "show_to_coder": True,
        "show_to_reviewer": True,
        "show_to_site_pi": True,
        "always_include": False,
        "is_default_start": True,
    },
    "vaneonatalperioddetails": {
        "display_label": "Neonatal Period",
        "nav_label": "Neonatal Period",
        "icon_name": "fa-baby",
        "render_mode": "table_sections",
        "show_to_coder": True,
        "show_to_reviewer": True,
        "show_to_site_pi": True,
        "always_include": False,
        "is_default_start": False,
    },
    "vainjuriesdetails": {
        "display_label": "Injuries",
        "nav_label": "Injuries",
        "icon_name": "fa-first-aid",
        "render_mode": "table_sections",
        "show_to_coder": True,
        "show_to_reviewer": True,
        "show_to_site_pi": True,
        "always_include": False,
        "is_default_start": False,
    },
    "vahealthhistorydetails": {
        "display_label": "Disease / Co-morbidity",
        "nav_label": "Disease/Co-morbidity",
        "icon_name": "fa-history",
        "render_mode": "health_history_summary",
        "show_to_coder": True,
        "show_to_reviewer": True,
        "show_to_site_pi": True,
        "always_include": False,
        "is_default_start": False,
    },
    "vageneralsymptoms": {
        "display_label": "General Symptoms",
        "nav_label": "General Symptoms",
        "icon_name": "fa-thermometer",
        "render_mode": "table_sections",
        "show_to_coder": True,
        "show_to_reviewer": True,
        "show_to_site_pi": True,
        "always_include": False,
        "is_default_start": False,
    },
    "varespiratorycardiacsymptoms": {
        "display_label": "Respiratory / Cardiac",
        "nav_label": "Respiratory / Cardiac",
        "icon_name": "fa-lungs",
        "render_mode": "table_sections",
        "show_to_coder": True,
        "show_to_reviewer": True,
        "show_to_site_pi": True,
        "always_include": False,
        "is_default_start": False,
    },
    "vaabdominalsymptoms": {
        "display_label": "Abdominal",
        "nav_label": "Abdominal",
        "icon_name": "fa-capsules",
        "render_mode": "table_sections",
        "show_to_coder": True,
        "show_to_reviewer": True,
        "show_to_site_pi": True,
        "always_include": False,
        "is_default_start": False,
    },
    "vaneurologicalsymptoms": {
        "display_label": "Neurological",
        "nav_label": "Neurological",
        "icon_name": "fa-brain",
        "render_mode": "table_sections",
        "show_to_coder": True,
        "show_to_reviewer": True,
        "show_to_site_pi": True,
        "always_include": False,
        "is_default_start": False,
    },
    "vaskinmucosalsymptoms": {
        "display_label": "Skin / Mucosal / Others",
        "nav_label": "Skin / Mucosal / Others",
        "icon_name": "fa-allergies",
        "render_mode": "table_sections",
        "show_to_coder": True,
        "show_to_reviewer": True,
        "show_to_site_pi": True,
        "always_include": False,
        "is_default_start": False,
    },
    "vaneonatalfeedingsymptoms": {
        "display_label": "Neonatal Specific",
        "nav_label": "Neonatal Specific",
        "icon_name": "fa-baby-carriage",
        "render_mode": "table_sections",
        "show_to_coder": True,
        "show_to_reviewer": True,
        "show_to_site_pi": True,
        "always_include": False,
        "is_default_start": False,
    },
    "vamaternalsymptoms": {
        "display_label": "Maternal",
        "nav_label": "Maternal",
        "icon_name": "fa-female",
        "render_mode": "table_sections",
        "show_to_coder": True,
        "show_to_reviewer": True,
        "show_to_site_pi": True,
        "always_include": False,
        "is_default_start": False,
    },
    "vahealthserviceutilisation": {
        "display_label": "Health Service Utilization",
        "nav_label": "Health Service Utilization",
        "icon_name": "fa-hospital-alt",
        "render_mode": "table_sections",
        "show_to_coder": True,
        "show_to_reviewer": True,
        "show_to_site_pi": True,
        "always_include": False,
        "is_default_start": False,
    },
    "vanarrationanddocuments": {
        "display_label": "Narration / Documents / COD",
        "nav_label": "Narration / Documents / COD",
        "icon_name": "fa-file-medical-alt",
        "render_mode": "attachments",
        "show_to_coder": True,
        "show_to_reviewer": True,
        "show_to_site_pi": True,
        "always_include": True,
        "is_default_start": False,
    },
    "social_autopsy": {
        "display_label": "Social Autopsy",
        "nav_label": "Social Autopsy",
        "icon_name": "fa-users",
        "render_mode": "table_sections",
        "show_to_coder": True,
        "show_to_reviewer": True,
        "show_to_site_pi": True,
        "always_include": False,
        "is_default_start": False,
    },
}
