"""app/services/xform_expression_evaluator.py is a Python port of
``vendor/who-va-2022/src/engine/expression.ts``, the only place in the
system that can evaluate an XLSForm ``relevant``/``constraint``/
``calculation`` expression. Two independent implementations of the same
semantics is the risk (beads digitva-cal.1); this is the test that keeps
them from drifting apart unnoticed.

``vendor/who-va-2022/src/generated/expression-conformance-corpus.json`` is
generated by ``tooling/who-va-2022/build-expression-corpus.mjs`` running the
real TypeScript engine against a set of answer fixtures -- see that script's
own header for how the fixtures are chosen. Every case here is required to
match exactly; there is no "close enough".
"""
from __future__ import annotations

import json
import math
import unittest
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

from app.services.xform_expression_evaluator import (
    ExpressionEvaluationOptions,
    evaluate_expression,
    parse_expression,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
CORPUS_PATH = (
    REPO_ROOT
    / "vendor/who-va-2022/src/generated/expression-conformance-corpus.json"
)


def _load_corpus() -> dict:
    with CORPUS_PATH.open(encoding="utf-8") as handle:
        return json.load(handle)


def _now_from_corpus(corpus: dict) -> datetime:
    return datetime.fromisoformat(corpus["now"]).replace(tzinfo=ZoneInfo(corpus["timezone"]))


class ExpressionConformanceCorpusTests(unittest.TestCase):
    """One test per corpus case, generated at class-body time so a failure
    names the exact expression and scenario, not just "some case failed"."""

    @classmethod
    def setUpClass(cls) -> None:
        cls.corpus = _load_corpus()
        cls.now = _now_from_corpus(cls.corpus)

    def test_corpus_is_not_empty_and_covers_both_branches(self) -> None:
        # Present first, so a corpus regeneration that silently emptied the
        # file cannot make every other test in this class vacuously pass.
        self.assertGreater(len(self.corpus["entries"]), 0)
        results = [case["result"] for entry in self.corpus["entries"] for case in entry["cases"]]
        self.assertIn(True, results)
        self.assertIn(False, results)

    def test_every_case_matches_the_typescript_engine(self) -> None:
        failures: list[str] = []
        checked = 0
        for entry in self.corpus["entries"]:
            source = entry["source"]
            if entry["parseError"]:
                with self.assertRaises(Exception, msg=f"expected a parse error for {source!r}"):
                    parse_expression(source)
                continue
            ast = parse_expression(source)
            for case in entry["cases"]:
                checked += 1
                options = ExpressionEvaluationOptions(
                    current_value=case["currentValue"], now=self.now
                )
                try:
                    actual = evaluate_expression(ast, case["data"], options)
                except Exception as error:  # noqa: BLE001 - recorded, not raised, to report every mismatch at once
                    if case["error"] is None:
                        failures.append(
                            f"{source!r} [{case['scenario']}]: raised {error!r}, expected {case['result']!r}"
                        )
                    continue
                if case["error"] is not None:
                    failures.append(
                        f"{source!r} [{case['scenario']}]: returned {actual!r}, expected an error ({case['error']})"
                    )
                    continue
                if case["resultIsNaN"]:
                    if not (isinstance(actual, float) and math.isnan(actual)):
                        failures.append(
                            f"{source!r} [{case['scenario']}]: returned {actual!r}, expected NaN"
                        )
                    continue
                if not _matches(actual, case["result"]):
                    failures.append(
                        f"{source!r} [{case['scenario']}]: returned {actual!r}, expected {case['result']!r}"
                    )
        self.assertGreater(checked, 0)
        self.assertEqual(failures, [], f"{len(failures)} of {checked} corpus cases diverged")

    def test_devanagari_digit_reads_false_under_ascii_regex(self) -> None:
        # Pins the specific divergence trap beads digitva-cal.1 names: an
        # engine-level failure here (rather than a generic corpus mismatch
        # above) is a regression in `regex()`'s re.ASCII usage specifically.
        entry = next(e for e in self.corpus["entries"] if "\\d" in e["source"])
        ast = parse_expression(entry["source"])
        digit_case = next(
            c for c in entry["cases"] if any("०" <= ch <= "९" for ch in (c["currentValue"] or ""))
        )
        options = ExpressionEvaluationOptions(current_value=digit_case["currentValue"], now=self.now)
        self.assertEqual(evaluate_expression(ast, digit_case["data"], options), False)


def _matches(actual: object, expected: object) -> bool:
    """JSON has no float/int distinction where JavaScript has none either
    (both are IEEE-754 doubles); the corpus's `12` and this module's `12.0`
    are the same value."""
    if isinstance(expected, bool) or isinstance(actual, bool):
        return actual is expected
    if isinstance(expected, (int, float)) and isinstance(actual, (int, float)):
        return float(actual) == float(expected)
    return actual == expected


if __name__ == "__main__":
    unittest.main()
