va_mapping_choice = {
    "Site": {
        "TR01": "Agartala Government Medical College, Tripura",
        "KL01": "Sree Chitra Tirunal Institute for Medical Sciences and Technology, Trivandrum",
        "NC01": "All India Institute of Medical Sciences, New Delhi",
        "KA01": "K.L.E. Academy of Higher Education & Research, Belagavi",
    },
    "Id10010b": {
        "female": "Female",
        "male": "Male",
        "undetermined": "Ambiguous/Intersex",
    },
    "Id10007a": {
        "female": "Female",
        "male": "Male",
        "undetermined": "Ambiguous/Intersex",
    },
    "Id10019": {
        "female": "Female",
        "male": "Male",
        "undetermined": "Ambiguous/Intersex",
    },
    "language": {
        "english": "English",
        "hindi": "Hindi",
        "marathi": "Marathi",
        "kannada": "Kannada",
        "malayalam": "Malayalam",
        "bangla": "Bangla",
    },
    "survey_state": {
        "16": "Tripura",
        "32": "Kerala",
        "6": "Haryana",
        "29": "Karnataka",
    },
    "survey_district": {
        "88": "Faridabad",
        "555": "Belagavi",
        "601": "Thiruvananthapuram",
        "289": "West Tripura",
    },
    "Id10002": {
        "high": "High",
        "low": "Low",
        "veryl": "Very low",
    },
    "Id10003": {
        "high": "High",
        "low": "Low",
        "veryl": "Very low",
    },
    "Id10004": {
        "wet": "Wet",
        "dry": "Dry",
        "DK": "Doesn't know",
    },
    "Id10008": {
        "parent": "Parent",
        "child": "Child",
        "family_member": "Other family member",
        "friend": "Friend",
        "spouse": "Spouse",
        "health_worker": "Health worker",
        "public_official": "Public official",
        "another_relationship": "Another relationship",
        "Ref": "Refused to answer",
    },
    "Id10009": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10487": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10064": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10104": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10105": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10107": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10377": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10109": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10110": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10111": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10112": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10113": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10114": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10115": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10116": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10125": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10126": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10127": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10128": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10129": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10482": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10483": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10130": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10131": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10132": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10133": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10134": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10135": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10136": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10137": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10138": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10139": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10140": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10141": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10142": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10143": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10144": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10077": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10079": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10082": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10083": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10084": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10085": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10086": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10087": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10089": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10091": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10092": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10093": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10096": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10094": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10095": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10097": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10098": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10099": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10100": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10408": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10123": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10147": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10149": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10153": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10155": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10156": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10157": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10158": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10159": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10170": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10171": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10166": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10172": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10173_a": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10174": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10175": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10181": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10185": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10186": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10188": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10189": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10189_1": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10191": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10192": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10194": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10195": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10200": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10204": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10207": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10208": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10212": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10214": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10217": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10220": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10222": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10275": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10276": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10223": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10226": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10224": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10230": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10231": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10227": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10229": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10233": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10236": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10237": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10238": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10239": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10240": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10242": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10243": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10244": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10245": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10246": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10247": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10249": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10251": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10252": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10254": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10253": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10255": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10256": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10257": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10258": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10259": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10260": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10261": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10262_c": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10265": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10267": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10268": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10269": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10271": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10272": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10273": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10277": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10278": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10279": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10281": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10282": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10283": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10284": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10286": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10287": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10288": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10289": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10485": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10486": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10294": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10296": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10299": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10300": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10301": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10302": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10305": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10312": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10313": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10314": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10306": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10334": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10333": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10308": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10304": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10304_a": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10321": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10322_a": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10325": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10327": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10323": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10324": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10328": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10329_a": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10329_b": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10322_b": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10331": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10342": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10343": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10344": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10330": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10320": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10340": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10354": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10363": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10365": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10369": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10370": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10371": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10372": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10373": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10383": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10384": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10387": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10388": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10389": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10391": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10393": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10395": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10396": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10397": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10398": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10399": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10400": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10401": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10402": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10403": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10404": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10405": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10406": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10411": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10413": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10413_b": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10414": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10414_b": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10418": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10419": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10420": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10421": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10422": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10423": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10424": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10425": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10426": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10435": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10446": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10013": {
        "yes": "Yes",
        "no": "No",
    },
    "Id10051": {
        "yes": "Yes",
        "no": "No",
    },
    "Id10366_check": {
        "yes": "Yes",
        "no": "No",
    },
    "Id10069_a": {
        "yes": "Yes",
        "no": "No",
    },
    "Id10071_check": {
        "yes": "Yes",
        "no": "No",
    },
    "Id10020": {
        "yes": "Yes",
        "no": "No",
        "ref": "Refused to answer",
    },
    "Id10022": {
        "yes": "Yes",
        "no": "No",
        "ref": "Refused to answer",
    },
    "age_group": {
        "neonate": "Neonate",
        "child": "Child",
        "adult": "Adult",
    },
    "age_child_unit": {
        "days": "Days",
        "months": "Months",
        "years": "Years",
    },
    "Id10058": {
        "hospital": "Hospital",
        "other_health_facility": "Other health facility",
        "home": "Home",
        "on_route_to_hospital_or_facility": "On route to hospital or facility",
        "other": "Other",
        "DK": "Doesn't know",
        "Ref": "Refused to answer",
    },
    "Id10052": {
        "citizen_at_birth": "Citizen at birth",
        "naturalized_citizen": "Naturalized citizen",
        "foreign_national": "Foreign national",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10059": {
        "single": "Single",
        "married": "Married",
        "partner": "Life partner",
        "divorced": "Divorced",
        "widowed": "Widowed",
        "too_young_to_be_married": "Too young to be married",
        "DK": "Doesn't know",
        "Ref": "Refused to answer",
    },
    "Id10063": {
        "no_formal_education": "No formal education",
        "primary_school": "Primary school",
        "secondary_school": "Secondary school",
        "higher_than_secondary_school": "Higher than secondary school",
        "DK": "Doesn't know",
        "Ref": "Refused to answer",
    },
    "Id10065": {
        "mainly_unemployed": "Mainly unemployed",
        "mainly_employed": "Mainly employed",
        "home-maker": "Home-maker",
        "pensioner": "Pensioner",
        "student": "Student",
        "other": "Other",
        "DK": "Doesn't know",
        "Ref": "Refused to answer",
    },
    "Id10477": {
        "Chronic_kidney_disease": "Chronic kidney disease",
        "Dialysis": "Dialysis",
        "Fever": "Fever",
        "Heart_attack": "Heart attack",
        "Heart_problem": "Heart problem",
        "Jaundice": "Jaundice",
        "Liver_failure": "Liver failure",
        "Malaria": "Malaria",
        "Pneumonia": "Pneumonia",
        "Renal_kidney_failure": "Renal (kidney) failure",
        "Suicide": "Suicide",
        "nan": "None of the above words were mentioned",
    },
    "Id10478": {
        "abdomen": "Abdomen",
        "cancer": "Cancer",
        "dehydration": "Dehydration",
        "dengue": "Dengue fever",
        "diarrhea": "Diarrhoea",
        "fever": "Fever",
        "heart_problem": "Heart problems",
        "jaundice": "Jaundice (yellow skin or eyes)",
        "pneumonia": "Pneumonia",
        "rash": "Rash",
        "nan": "None of the above words were mentioned",
    },
    "Id10479": {
        "asphyxia": "Asphyxia",
        "incubator": "Incubator",
        "lung_problem": "Lung problem",
        "pneumonia": "Pneumonia",
        "preterm_delivery": "Preterm delivery",
        "respiratory_distress": "Respiratory distress",
        "nan": "None of the above words were mentioned",
    },
    "Id10376": {
        "before": "Before",
        "after": "After",
        "dk": "Don't know",
        "ref": "Refused to answer",
    },
    "Id10201_unit": {
        "days": "Days",
        "months": "Months",
        "DK": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10205_unit": {
        "days": "Days",
        "months": "Months",
        "DK": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10178_unit": {
        "hours": "Hours",
        "days": "Days",
        "DK": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10484": {
        "positive": "Positive",
        "negative": "Negative",
        "unclear": "Unclear",
        "dk": "Don't know",
        "ref": "Refused to answer",
    },
    "id10196_unit": {
        "hours": "Hours",
        "days": "Days",
        "months": "Months",
        "DK": "Doesn't know",
        "ref": "Refused to answer",
    },
    "id10161_unit": {
        "days": "Days",
        "months": "Months",
        "years": "Years",
        "DK": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10077_a": {
        "less": "Less or equal to 7 days",
        "more": "More than 7 days",
        "dk": "Don't know",
        "ref": "Refused to answer",
    },
    "id10120_unit": {
        "days": "Days",
        "months": "Months",
        "years": "Years",
        "DK": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10088": {
        "dog": "Dog",
        "snake": "Snake",
        "insect_or_scorpion": "Insect or scorpion",
        "other": "Other",
        "DK": "Doesn't know",
        "Ref": "Refused to answer",
    },
    "Id10148_units": {
        "days": "Days",
        "months": "Months",
        "DK": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10154_units": {
        "days": "Days",
        "months": "Months",
        "DK": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10167_units": {
        "days": "Days",
        "months": "Months",
        "DK": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10182_units": {
        "days": "Days",
        "months": "Months",
        "DK": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10184_units": {
        "days": "Days",
        "months": "Months",
        "DK": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10190_units": {
        "days": "Days",
        "months": "Months",
        "DK": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10209_units": {
        "days": "Days",
        "months": "Months",
        "DK": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10213_units": {
        "days": "Days",
        "months": "Months",
        "DK": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10232_units": {
        "days": "Days",
        "months": "Months",
        "DK": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10248_units": {
        "days": "Days",
        "months": "Months",
        "DK": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10250_units": {
        "days": "Days",
        "months": "Months",
        "DK": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10266_units": {
        "days": "Days",
        "months": "Months",
        "DK": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10274_units": {
        "days": "Days",
        "months": "Months",
        "DK": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10216_units": {
        "hours": "Hours",
        "days": "Days",
        "DK": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10262_units": {
        "days": "Days",
        "weeks": "Weeks",
        "months": "Months",
        "DK": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10150": {
        "mild": "Mild",
        "severe": "Severe",
        "DK": "Doesn't know",
        "Ref": "Refused to answer",
    },
    "Id10151": {
        "continuous": "Continuous",
        "on_and_off": "On and off",
        "nightly": "Only at night",
        "DK": "Doesn't know",
        "Ref": "Refused to answer",
    },
    "Id10165": {
        "continuous": "Continuous",
        "on_and_off": "On and off",
        "DK": "Doesn't know",
        "Ref": "Refused to answer",
    },
    "Id10173_nc": {
        "stridor": "Stridor",
        "grunting": "Grunting",
        "wheezing": "Wheezing",
        "no": "Not like Stridor or Grunting or Wheezing",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10199": {
        "upper_right": "Upper right abdomen",
        "upper_left": "Upper left abdomen",
        "lower_right": "Lower right abdomen",
        "lower_left": "Lower left abdomen",
        "all_over": "All over the abdomen",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10203": {
        "rapidly": "Rapidly",
        "slowly": "Slowly",
        "DK": "Doesn't know",
        "Ref": "Refused to answer",
    },
    "Id10235": {
        "face": "Face",
        "trunk": "Trunk or abdomen",
        "extremities": "Extremities",
        "everywhere": "Everywhere",
        "DK": "Doesn't know",
        "Ref": "Refused to answer",
    },
    "Id10337": {
        "hospital": "Hospital",
        "other_health_facility": "Other health facility",
        "home": "Home",
        "on_route_to_hospital_or_facility": "On route to hospital or facility",
        "other": "Other",
        "DK": "Doesn't know",
        "Ref": "Refused to answer",
    },
    "Id10310": {
        "yes": "I confirm this was not a maternal death",
    },
    "Id10317": {
        "singleton": "singleton",
        "twins": "twins",
        "triplets": "triplets or more",
        "dk": "Don't know",
        "ref": "Refused to answer",
    },
    "Id10385": {
        "green_or_brown": "Green or brown",
        "clear": "Clear (normal)",
        "other": "Other",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10413_a": {
        "months": "Months",
        "years": "Years",
        "dk": "Don't know",
        "ref": "Refused to answer",
    },
    "Id10414_a": {
        "months": "Months",
        "years": "Years",
        "dk": "Don't know",
        "ref": "Refused to answer",
    },
    "Id10462": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "Id10463": {
        "yes": "Yes",
        "no": "No",
        "dk": "Doesn't know",
        "ref": "Refused to answer",
    },
    "md_available": {
        "yes": "Yes",
        "no": "No",
        "ref": "Refused to answer",
    },
}
