va_mapping_summary = {
    "vademographicdetails": {
        "Id10411": "Drinks alcohol",
        "Id10413": "Smokes tobacco",
        "Id10413_b": "Smokes daily",
        "Id10414": "Chew / Sniffs tobacco",
        "Id10414_b": "Chew / Sniff's tobacco daily",
        "Id10487": "In contact with someone with COVID-19 symptoms / or positive results 2 week before death",
    },
    "vaneonatalperioddetails": {
        "Id10354": "Child part of a multiple birth",
        "Id10387": "Normal vaginal delivery, without forceps or vacuum",
        "Id10388": "Vaginal delivery, with forceps or vacuum",
        "Id10389": "Caesarean section delivery",
        "Id10369": "Complications during labour / delivery",
        "Id10383": "Born 24 hours or more after the water broke",
        "Id10384": "Liquor foul smelling",
        "Id10403": "Bottom, feet, arm, hand come out of the vagina before head",
        "Id10404": "Umbilical cord wrapped around neck",
        "Id10405": "Umbilical cord delivered first",
        "Id10104": "Never cried",
        "Id10105": "Never cried immediately after birth",
        "Id10107": "Stopped crying",
        "Id10377": "Stopped moving in womb",
        "Id10109": "Never move after being delivered",
        "Id10110": "Never breathe",
        "Id10111": "Never breathe immediately after birth",
        "Id10112": "Breathing problem",
        "Id10113": "Aided assistance to breathe",
        "Id10114": "Born dead",
        "Id10115": "Bruises / Injury on body",
        "Id10116": "Body was soft, discoloured, skin peeling away",
        "Id10363": "Weighed under 2.5 kg at birth",
        "Id10365": "Weighed over 4.5 kg at birth",
        "Id10406": "Blue in colour at birth",
        "Id10284": "Cold to touch",
        "Id10286": "Lethargic after normal activity",
        "Id10287": "Redness or pus oozing from umbilical cord",
        "Id10288": "Skin ulcer or sore",
        "Id10289": "Yellow skin, palms or soles",
        "Id10370": "Physically abnormal at delivery",
        "Id10371": "Swelling or defect on back at birth",
        "Id10372": "Large head at birth",
        "Id10373": "Small head at birth",
        "Id10391": "Mother didn't received any vaccinations since reaching adulthood including during this pregnancy",
        "Id10393": "Mother didn't receive tetanus toxoid (TT) vaccine",
        "Id10395": "Mother suffer from fever during labour",
        "Id10396": "Mother suffered from high blood pressure (last 3 months of pregnancy, labour or delivery)",
        "Id10397": "Mother have diabetes mellitus",
        "Id10398": "Mother have foul smelling vaginal discharge during pregnancy / after delivery",
        "Id10399": "Mother suffered from convulsions (last 3 months of pregnancy, labour or delivery)",
        "Id10400": "Mother suffered from blurred vision (during last 3 months of pregnancy)",
        "Id10401": "Mother had severe anemia",
        "Id10402": "Mother had vaginal bleeding (during last 3 months of pregnancy but before labour started)",
    },
    "vainjuriesdetails": {
        "Id10077": "Injury or accident led to death",
        "Id10079": "Road transport injury",
        "Id10082": "Non-road transport injury",
        "Id10083": "Injured in a fall",
        "Id10084": "Poisoning",
        "Id10085": "Drowning",
        "Id10086": "Venomous bite / sting from animal or insect",
        "Id10087": "Injured by an animal / insect",
        "Id10089": "Burns/fire",
        "Id10091": "Firearm",
        "Id10092": "Stabbed, cut or pierced",
        "Id10093": "Strangled",
        "Id10096": "Electrocuted",
        "Id10094": "Injured by blunt force",
        "Id10095": "Injured by force of nature",
        "Id10097": "Some injury",
        "Id10098": "Accident",
        "Id10099": "Self-inflicted harm",
        "Id10100": "Injury inflicted by someone else",
    },
    "vahealthhistorydetails": {
        "Id10408": "Never grew normally before illness started",
        "Id10125": "Tuberculosis",
        "Id10126": "HIV",
        "Id10127": "AIDS",
        "Id10128": "Tested positive for malaria",
        "Id10129": "Tested negative for malaria",
        "Id10482": "COVID-19",
        "Id10483": "Recent test for COVID-19",
        "Id10130": "Dengue fever",
        "Id10131": "Measles",
        "Id10132": "High blood pressure",
        "Id10133": "Heart disease",
        "Id10134": "Diabetes",
        "Id10135": "Asthma",
        "Id10136": "Epilepsy",
        "Id10137": "Cancer",
        "Id10138": "Chronic Obstructive Pulmonary Disease (COPD)",
        "Id10139": "Dementia",
        "Id10140": "Depression",
        "Id10141": "Stroke",
        "Id10142": "Sickle cell disease",
        "Id10143": "Kidney disease",
        "Id10144": "Liver disease",
    },
    "vageneralsymptoms": {
        "Id10123": "Died suddenly",
        "Id10121": "Illness duration (in months)",
        "Id10122": "Illness duration (in years)",
        "Id10120": "Illness duration (in days)",
        "Id10147": "Fever",
        "Id10149": "Fever continued until death",
        "Id10233": "Skin rash",
        "Id10236": "Measles rash",
        "Id10265": "Yellow discoloration of the eyes",
        "Id10267": "Hair change in color to a reddish or yellowish color",
        "Id10268": "Look pale or have pale palms, eyes or nail beds",
        "Id10269": "Sunken eyes",
        "Id10252": "General swelling of the body",
        "Id10485": "Extreme fatigue",
        "Id10247": "Puffiness of face",
        "Id10249": "Swollen legs or feet",
        "Id10251": "Both feet swollen",
    },
    "varespiratorycardiacsymptoms": {
        "Id10153": "Cough",
        "Id10155": "Cough productive with sputum",
        "Id10156": "Cough severe",
        "Id10157": "Hemoptysis",
        "Id10158": "Whooping sound when coughing",
        "Id10159": "Difficulty breathing",
        "Id10170": "Unable to carry out daily routines due to breathlessness",
        "Id10171": "Orthopnea",
        "Id10166": "Fast breathing",
        "Id10172": "Chest in-drawing",
        "Id10173_a": "Wheezing",
        "Id10174": "Chest pain",
        "Id10175": "Chest pain severe",
    },
    "vaabdominalsymptoms": {
        "Id10181": "Diarrhoea",
        "Id10185": "Diarrhoea continued until death",
        "Id10186": "Blood in stools",
        "Id10188": "Vomit",
        "Id10189": "Vomitted week preceding death",
        "Id10189_1": "Vomitted every time when ate or drank",
        "Id10191": "Blood in vomit",
        "Id10192": "Black colored vomit",
        "Id10194": "Abdominal pain",
        "Id10195": "Abdominal pain severe",
        "Id10200": "Protruding abdomen",
        "Id10204": "Mass in abdomen",
        "Id10223": "Urine problems",
        "Id10226": "Blood in urine",
        "Id10224": "Anuria",
    },
    "vaneurologicalsymptoms": {
        "Id10207": "Severe headache",
        "Id10486": "Loss, change or decreased sense of smell or taste",
        "Id10212": "Mental confusion",
        "Id10214": "Unconscious",
        "Id10217": "Unconsciousness started suddenly, quickly",
        "Id10258": "Paralysis",
        "Id10259": "Paralysis of one side of body",
        "Id10260": "Paralysis of both legs",
        "Id10208": "Stiff or painful neck",
        "Id10220": "Generalized convulsions",
        "Id10222": "Unconscious immediately after convulsion",
        "Id10275": "Convulsions started first 24 hours of life",
        "Id10276": "Convulsions started more than 24 hours after birth",
        "Id10261": "Difficulty / pain in swallowing",
        "Id10262_c": "Swallowing become impossible",
    },
    "vaskinmucosalsymptoms": {
        "Id10230": "Ulcer on the foot",
        "Id10231": "Ulcer on foot have pus",
        "Id10227": "Ulcers / sores on body",
        "Id10229": "Ulcers or sores had pus",
        "Id10233": "Skin rash",
        "Id10236": "Measles rash",
        "Id10254": "Lumps or sores in mouth",
        "Id10255": "Lumps on neck",
        "Id10256": "Lumps on armpit",
        "Id10257": "Lumps on groin",
        "Id10237": "Shingles / herpes zoster",
        "Id10238": "Skin flake off in patches",
        "Id10239": "Areas of skin turned black",
        "Id10240": "Areas of skin with redness / swelling",
        "Id10242": "Bleed from nose, mouth or anus",
        "Id10243": "Noticeable weight loss",
        "Id10244": "Severely thin or wasted",
        "Id10245": "Whitish rash in mouth / on tongue",
        "Id10246": "Stiffness of the whole body / was unable to open the mouth",
    },
    "vaneonatalfeedingsymptoms": {
        "Id10271": "Not able to suckle / bottle-feed within the first 24 hours after birth",
        "Id10272": "Never suckle in normal way",
        "Id10273": "Stop suckling",
        "Id10277": "Body become stiff, with back arched backwards",
        "Id10278": "Bulging / raised fontanelle",
        "Id10279": "Sunken fontanelle",
        "Id10281": "Unresponsive / unconscious",
        "Id10282": "Unresponsive / unconscious within 24 hours of birth",
        "Id10283": "Unresponsive / unconscious more than 24 hours after birth",
    },
    "vamaternalsymptoms": {
        "Id10296": "Never had period or menstruate",
        "Id10299": "Menstrual period didn't stop naturally",
        "Id10300": "Vaginal bleeding after cessation of menstruation",
        "Id10301": "Excessive vaginal bleeding in the week prior to death",
        "Id10294": "Lump(s) / ulcer(s) in breast",
        "Id10340": "Operation to remove uterus shortly before death",
        "Id10302": "Period overdue (at death)",
        "Id10305": "Pregnant and not yet in labour (during death)",
        "Id10312": "Died during labour or delivery",
        "Id10314": "Died within 24 hours after delivering a baby",
        "Id10306": "Died within 6 weeks after delivering a baby",
        "Id10334": "Pregnancy ended in abortion / miscarriage within 6 weeks before death",
        "Id10333": "Attempt to terminate pregnancy",
        "Id10308": "Died in less than 1 year after delivery, abortion or miscarriage",
        "Id10320": "Previous Caesarean section exists",
        "Id10321": "High blood pressure during pregnancy",
        "Id10323": "Convulsions during the last 3 months of pregnancy and/or after delivery",
        "Id10324": "Blurred vision during the last 3 months of pregnancy and/or after delivery",
        "Id10304": "Sharp abdominal pain in first 3 months of pregnancy",
        "Id10304_a": "Fainted when had the sharp abdominal pain",
        "Id10322_a": "Foul smelling vaginal discharge during pregnancy",
        "Id10325": "Bleeding during pregnancy",
        "Id10329_b": "Excessive bleeding during or after abortion or miscarriage",
        "Id10327": "Vaginal bleeding during the last 3 months of pregnancy but before labour started",
        "Id10342": "Normal vaginal delivery, without forceps or vacuum",
        "Id10343": "Vaginal delivery, with forceps or vacuum",
        "Id10344": "Caesarean section delivery",
        "Id10331": "Deliver abnormally positioned baby",
        "Id10330": "Placenta in-completely delivered",
        "Id10328": "Excessive bleeding during labour / delivery",
        "Id10322_b": "Foul smelling vaginal discharge after delivery/abortion",
        "Id10329_a": "Excessive bleeding after delivery",
    },
    "vahealthserviceutilisation": {
        "Id10418": "Received treatment fo illness that led to death",
        "Id10419": "Received oral rehydration salts",
        "Id10420": "Received (or need) intravenous fluids (drip) treatment",
        "Id10421": "Received (or need) a blood transfusion",
        "Id10422": "Received (or need) treatment/food through a tube passed through the nose",
        "Id10423": "Received (or need) injectable antibiotics",
        "Id10424": "Received (or need) antiretroviral therapy (ART)",
        "Id10425": "Had (or need) an operation for the illness",
        "Id10426": "Operation within 1 month before death",
        "Id10435": "Health care worker shared the cause of death",
        "Id10436": "Cause of death / comment by the health worker",
        "Id10446": "Mother had HIV/AIDS as per the health worker",
    },
    "vanarrationanddocuments": {
        "Id10462": "Medical certificate of cause of death available",
    },
}
