"""Build the paste-ready ODK rows for the DORIS support questions.

Writes docs/kb/WHO_VA_2022_Docs/odk-doris-support-rows.xlsx (sheets
``survey``, ``choices``, ``notes``) and the Markdown copy beside it,
odk-doris-support-rows.md, from
vendor/who-va-2022/src/generated/odk-doris-support-rows.json. That file is
generated by tooling/who-va-2022/build-odk-doris-rows.mjs from the web
form's own ``doris_support_whova_2022`` extension
(vendor/who-va-2022/src/digitva-extension.ts), so ODK and web share one
definition and one payload shape (bead digitva-hln). The blocks are Annex A
(A1-A10) of docs/kb/DORIS/who-va-2022-doris-consistency-proposal.md.

Columns and row numbers come from the ND01 workbook
(docs/kb/WHO_VA_2022_Docs/ND01_ICMRVA_WHOVA2022.xlsx): the ``survey`` and
``choices`` sheets use ND01's own header, in ND01's order, so a block pastes
straight in; a changed WHO row is ND01's row with only the changed cells
replaced. A choice list ND01 already has is not repeated. An added row's
``agegroup`` is its question's ``ageGroup``; its ``order`` is text, the
order of the ND01 row it follows plus ``.1``, ``.2``... (``.01`` when more
than nine rows share that order), so WHO's orders stay unchanged. Fails if an
anchor or a changed row is missing from ND01, or if ND01 has a list of the
same name with other values.

Run after ``npm run build:odk-doris-rows`` (tooling/who-va-2022), inside
the app container:

    docker compose exec -T minerva_app_service uv run --no-sync \\
        python tooling/who-va-2022/build_odk_doris_rows.py
"""

from __future__ import annotations

import json
from pathlib import Path

import openpyxl

REPO = Path(__file__).resolve().parents[2]
KB = REPO / "docs/kb/WHO_VA_2022_Docs"
ND01 = KB / "ND01_ICMRVA_WHOVA2022.xlsx"
ROWS_JSON = REPO / "vendor/who-va-2022/src/generated/odk-doris-support-rows.json"
OUT_XLSX = KB / "odk-doris-support-rows.xlsx"
OUT_MD = KB / "odk-doris-support-rows.md"
LAST_UPDATED = "2026-09-29"

LABEL = "label::English (en)"
HINT = "hint::English (en)"
AGREED = "agreed for deployment"
PROPOSED = "proposed"
# The generated rows' plain column names, as ND01's English columns.
COLUMN = {"label": LABEL, "hint": HINT}


def load_blocks() -> list[dict]:
    return json.loads(ROWS_JSON.read_text(encoding="utf-8"))["blocks"]


def _rows(sheet) -> tuple[list[str], list[dict]]:
    header = [cell.value for cell in sheet[1]]
    rows = []
    for number, cells in enumerate(sheet.iter_rows(min_row=2), start=2):
        values = {header[i]: cell.value for i, cell in enumerate(cells) if i < len(header) and header[i]}
        values["_row"] = number
        rows.append(values)
    return header, rows


def _row_named(rows: list[dict], name: str) -> dict:
    for values in rows:
        if values.get("name") == name:
            return values
    raise SystemExit(f"ND01 has no survey row named {name}")


def _group_end(rows: list[dict], group: str) -> int:
    begin = _row_named(rows, group)
    depth = 0
    for values in rows:
        if values["_row"] < begin["_row"]:
            continue
        kind = (values.get("type") or "").strip()
        if kind.startswith("begin"):
            depth += 1
        elif kind.startswith("end") and kind != "end":
            depth -= 1
            if depth == 0:
                return values["_row"]
    raise SystemExit(f"ND01 group {group} never closes")


def _anchor_row(block: dict, rows: list[dict]) -> int:
    """The ND01 row a block's new rows go after, or the row it changes."""
    odk = block["odk"]
    if "afterGroupEnd" in odk:
        return _group_end(rows, odk["afterGroupEnd"])
    if "after" in odk:
        return _row_named(rows, odk["after"])["_row"]
    return max(_row_named(rows, change["name"])["_row"] for change in block["change"])


def _anchor_order(block: dict, rows: list[dict]):
    """The ``order`` of a block's anchor row, or of the nearest ND01 row above it that has one."""
    anchor = _anchor_row(block, rows)
    for values in reversed(rows):
        if values["_row"] <= anchor and values.get("order") not in (None, ""):
            return values["order"]
    raise SystemExit(f"{block['id']}: no ND01 row at or above row {anchor} has an order")


def _new_orders(blocks: list[dict], rows: list[dict]) -> dict[str, str]:
    """Each added row's ``order``: its anchor's order plus a suffix in insertion order."""
    by_base: dict[str, list[str]] = {}
    for block in blocks:
        if block["survey"]:
            base = str(_anchor_order(block, rows))
            by_base.setdefault(base, []).extend(entry["name"] for entry in block["survey"])
    orders = {}
    for base, names in by_base.items():
        width = 2 if len(names) > 9 else 1
        for number, name in enumerate(names, start=1):
            orders[name] = f"{base}.{number:0{width}d}"
    return orders


def _position(block: dict, rows: list[dict]) -> str:
    odk = block["odk"]
    if "afterGroupEnd" in odk:
        return f"after the `end group` of `{odk['afterGroupEnd']}` (ND01 row {_anchor_row(block, rows)})"
    return f"after `{odk['after']}` (ND01 row {_anchor_row(block, rows)})"


def _new_choices(block: dict, nd01_lists: dict[str, list[str]]) -> list[dict]:
    """The block's choices, less the lists ND01 already has (checked equal)."""
    new = []
    for choice in block["choices"]:
        existing = nd01_lists.get(choice["list_name"])
        if existing is None:
            new.append(choice)
            continue
        wanted = [c["name"] for c in block["choices"] if c["list_name"] == choice["list_name"]]
        if existing != wanted:
            raise SystemExit(f"ND01 list {choice['list_name']} is {existing}, the extension's is {wanted}")
    return new


def render(blocks: list[dict], nd01) -> tuple[str, dict[str, list[list]]]:
    """The Markdown text and each sheet's rows (header first) for ``blocks``."""
    survey_header, survey_rows = _rows(nd01["survey"])
    choices_header, choice_rows = _rows(nd01["choices"])
    for column in ("order", "agegroup", "type", "name", LABEL, HINT, "required", "appearance", "constraint", "constraint_message", "relevant"):
        if column not in survey_header:
            raise SystemExit(f"ND01 survey has no column {column}")
    nd01_lists: dict[str, list[str]] = {}
    for values in choice_rows:
        if values.get("list_name"):
            nd01_lists.setdefault(values["list_name"], []).append(str(values.get("name")))

    orders = _new_orders(blocks, survey_rows)
    survey = [survey_header]
    choices = [choices_header]
    notes = [["block", "status", "survey rows", "choices rows", "what to do in ND01"]]
    md_blocks = []
    for block in blocks:
        steps, md_rows = [], []
        first = len(survey) + 1
        for change in block["change"]:
            existing = _row_named(survey_rows, change["name"])
            changed = {**{key: existing.get(key) for key in survey_header}, **change["cells"]}
            survey.append([changed.get(key) for key in survey_header])
            steps.append(f"replace ND01 row {existing['_row']} (`{change['name']}`): {', '.join(sorted(change['cells']))}")
            md_rows.append(changed)
        if block["survey"]:
            added = [entry["name"] for entry in block["survey"]]
            steps.append(f"add {', '.join(f'`{name}`' for name in added)} {_position(block, survey_rows)}")
            for entry in block["survey"]:
                row = {COLUMN.get(key, key): value for key, value in entry.items()}
                row["order"] = orders[entry["name"]]
                survey.append([row.get(key) or None for key in survey_header])
                md_rows.append(row)
        last = len(survey)
        new_choices = _new_choices(block, nd01_lists)
        choice_first = len(choices) + 1
        for choice in new_choices:
            row = {"list_name": choice["list_name"], "name": choice["name"], LABEL: choice["label"]}
            choices.append([row.get(key) for key in choices_header])
        choice_span = f"{choice_first}-{len(choices)}" if new_choices else ""
        notes.append([block["id"], block["status"], f"{first}-{last}", choice_span, "; ".join(steps)])
        md_blocks.append((block, steps, md_rows, new_choices))

    bottom_up = ", ".join(
        block["id"] for block in sorted(blocks, key=lambda block: _anchor_row(block, survey_rows), reverse=True)
    )
    order_note = (
        "ND01 row numbers are those of the unmodified workbook: apply the blocks bottom-up "
        f"({bottom_up}) so the numbers stay valid. Add the choices at the end of the choices "
        "sheet. An added row's order is its ND01 anchor's order plus .1, .2... (text, so WHO's "
        "orders stay unchanged). Hindi and other label columns follow each workbook's languages. Bump "
        "settings.version before deploying."
    )
    notes.append([])
    notes.append(["", "", "", "", order_note])
    return _markdown(md_blocks, order_note), {"survey": survey, "choices": choices, "notes": notes}


def build() -> None:
    nd01 = openpyxl.load_workbook(ND01, read_only=True)
    markdown, sheets = render(load_blocks(), nd01)
    out = openpyxl.Workbook()
    out.remove(out.active)
    for title, rows in sheets.items():
        sheet = out.create_sheet(title)
        for row in rows:
            sheet.append(row)
    out.save(OUT_XLSX)
    OUT_MD.write_text(markdown, encoding="utf-8")
    print(f"wrote {OUT_XLSX.relative_to(REPO)} and {OUT_MD.relative_to(REPO)}")


def _cell(column: str, value) -> str:
    text = "" if value is None else str(value).strip()
    if not text:
        return ""
    return f"`{text}`" if column in ("relevant", "constraint") else text.replace("|", "\\|")


MD_COLUMNS = ("order", "agegroup", "type", "name", LABEL, "relevant", "constraint", "constraint_message", "required", "appearance")


def _markdown(blocks, order_note: str) -> str:
    lines = [
        "---",
        "title: ODK XLSForm rows for DORIS prefill support",
        "doc_type: kb",
        "status: active",
        "owner: engineering",
        f"last_updated: {LAST_UPDATED}",
        "---",
        "",
        "# ODK XLSForm rows for DORIS prefill support",
        "",
        "Generated from the web form's `doris_support_whova_2022` extension",
        "(`vendor/who-va-2022/src/digitva-extension.ts`) by",
        "`tooling/who-va-2022/build-odk-doris-rows.mjs` and",
        "`tooling/who-va-2022/build_odk_doris_rows.py`; edit the extension, not",
        "this file. The same rows, paste-ready with ND01's own columns, are in",
        "`docs/kb/WHO_VA_2022_Docs/odk-doris-support-rows.xlsx` (sheets `survey`,",
        "`choices`, and `notes` saying where each block goes).",
        "",
        "The rows are Annex A (A1-A10) of",
        "`docs/kb/DORIS/who-va-2022-doris-consistency-proposal.md`. Every web form",
        "asks them, so ODK and web payloads share one shape and",
        "`app/services/doris_prefill.py` reads both alike (bead `digitva-hln`).",
        "A1, A2 and A3 are agreed for deployment; the rest are proposed, and the",
        "owner decides what each site deploys. Deploying to ODK Central (bump",
        "`settings.version`) is the owner's step.",
        "",
        "Positions are rows of the ND01 workbook (`ND01_ICMRVA_WHOVA2022.xlsx`).",
        order_note,
        "The other nine deployed workbooks carry the same questions at equivalent",
        "places. Columns not shown stay empty; only English is given.",
        "Integers follow the form's 88 = refused, 99 = don't know. `YES_NO_DK_REF`",
        "is the workbook's existing list.",
        "",
    ]
    for block, steps, rows, new_choices in blocks:
        lines += [f"## {block['id']}. {block['title']} ({block['status']})", ""]
        lines += [f"- {step[0].upper()}{step[1:]}." for step in steps]
        lines.append("")
        lines.append("| " + " | ".join(MD_COLUMNS) + " |")
        lines.append("|" + "---|" * len(MD_COLUMNS))
        for entry in rows:
            lines.append("| " + " | ".join(_cell(column, entry.get(column)) for column in MD_COLUMNS) + " |")
        lines.append("")
        if new_choices:
            lines += ["Choices:", "", "| list_name | name | label::English (en) |", "|---|---|---|"]
            lines += [f"| {c['list_name']} | {c['name']} | {c['label']} |" for c in new_choices]
            lines.append("")
        if block["odk"].get("note"):
            lines += [block["odk"]["note"], ""]
    return "\n".join(lines)


if __name__ == "__main__":
    build()
