"""add map_project_site_odk table

Revision ID: 1d95332b7d3c
Revises: 93c5cf3f4109
Create Date: 2026-03-10 04:08:43.498284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d95332b7d3c'
down_revision = '93c5cf3f4109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_project_site_odk',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.String(length=6), nullable=False),
    sa.Column('site_id', sa.String(length=4), nullable=False),
    sa.Column('odk_project_id', sa.Integer(), nullable=False),
    sa.Column('odk_form_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['va_project_master.project_id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['va_site_master.site_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'site_id', name='uq_map_project_site_odk_project_site')
    )
    with op.batch_alter_table('map_project_site_odk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_map_project_site_odk_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_map_project_site_odk_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_map_project_site_odk_site_id'), ['site_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_project_site_odk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_map_project_site_odk_site_id'))
        batch_op.drop_index(batch_op.f('ix_map_project_site_odk_project_id'))
        batch_op.drop_index(batch_op.f('ix_map_project_site_odk_id'))

    op.drop_table('map_project_site_odk')
    # ### end Alembic commands ###
