"""add progress_log to va_sync_runs

Revision ID: 576a75d5d354
Revises: s1t2u3v4w5x6
Create Date: 2026-03-13 04:01:01.820706

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '576a75d5d354'
down_revision = 's1t2u3v4w5x6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    for table_name in (
        'celery_periodictask',
        'celery_intervalschedule',
        'celery_crontabschedule',
        'celery_clockedschedule',
        'celery_periodictaskchanged',
        'celery_solarschedule',
    ):
        op.execute(sa.text(f'DROP TABLE IF EXISTS {table_name} CASCADE'))
    with op.batch_alter_table('map_project_site_odk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_map_project_site_odk_form_type_id'), ['form_type_id'], unique=False)

    with op.batch_alter_table('va_forms', schema=None) as batch_op:
        batch_op.drop_index('idx_va_forms_form_type')
        batch_op.create_index(batch_op.f('ix_va_forms_form_type_id'), ['form_type_id'], unique=False)

    with op.batch_alter_table('va_narrative_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_va_narrative_assessments_va_nqa_createdat'), ['va_nqa_createdat'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_narrative_assessments_va_nqa_id'), ['va_nqa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_narrative_assessments_va_nqa_status'), ['va_nqa_status'], unique=False)

    with op.batch_alter_table('va_sync_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress_log', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('va_sync_runs', schema=None) as batch_op:
        batch_op.drop_column('progress_log')

    with op.batch_alter_table('va_narrative_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_va_narrative_assessments_va_nqa_status'))
        batch_op.drop_index(batch_op.f('ix_va_narrative_assessments_va_nqa_id'))
        batch_op.drop_index(batch_op.f('ix_va_narrative_assessments_va_nqa_createdat'))

    with op.batch_alter_table('va_forms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_va_forms_form_type_id'))
        batch_op.create_index('idx_va_forms_form_type', ['form_type_id'], unique=False)

    with op.batch_alter_table('map_project_site_odk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_map_project_site_odk_form_type_id'))

    op.create_table('celery_solarschedule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event', postgresql.ENUM('dawn_astronomical', 'dawn_nautical', 'dawn_civil', 'sunrise', 'solar_noon', 'sunset', 'dusk_civil', 'dusk_nautical', 'dusk_astronomical', name='solarevent'), autoincrement=False, nullable=False, comment='The type of solar event when the job should run'),
    sa.Column('latitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=False, comment='Run the task when the event happens at this latitude'),
    sa.Column('longitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=False, comment='Run the task when the event happens at this longitude'),
    sa.CheckConstraint("latitude >= '-90'::integer::numeric AND latitude <= 90::numeric", name='celery_solarschedule_latitude_check'),
    sa.CheckConstraint("longitude >= '-180'::integer::numeric AND longitude <= 180::numeric", name='celery_solarschedule_longitude_check'),
    sa.PrimaryKeyConstraint('id', name='celery_solarschedule_pkey'),
    sa.UniqueConstraint('event', 'latitude', 'longitude', name='celery_solarschedule_event_latitude_longitude_key')
    )
    op.create_table('celery_periodictaskchanged',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_update', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='celery_periodictaskchanged_pkey')
    )
    op.create_table('celery_clockedschedule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('clocked_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='celery_clockedschedule_pkey')
    )
    op.create_table('celery_crontabschedule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('minute', sa.VARCHAR(length=240), autoincrement=False, nullable=False, comment='Cron Minutes to Run. Use "*" for "all". (Example: "0,30")'),
    sa.Column('hour', sa.VARCHAR(length=96), autoincrement=False, nullable=False, comment='Cron Hours to Run. Use "*" for "all". (Example: "8,20")'),
    sa.Column('day_of_week', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='Cron Days Of The Week to Run. Use "*" for "all", Sunday is 0 or 7, Monday is 1. (Example: "0,5")'),
    sa.Column('day_of_month', sa.VARCHAR(length=124), autoincrement=False, nullable=False, comment='Cron Days Of The Month to Run. Use "*" for "all". (Example: "1,15")'),
    sa.Column('month_of_year', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='Cron Months (1-12) Of The Year to Run. Use "*" for "all". (Example: "1,12")'),
    sa.Column('timezone', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='Timezone to Run the Cron Schedule on. Default is UTC.'),
    sa.PrimaryKeyConstraint('id', name='celery_crontabschedule_pkey')
    )
    op.create_table('celery_intervalschedule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('every', sa.INTEGER(), autoincrement=False, nullable=False, comment='Number of interval periods to wait before running the task again'),
    sa.Column('period', postgresql.ENUM('days', 'hours', 'minutes', 'seconds', 'microseconds', name='period'), autoincrement=False, nullable=False, comment='The type of period between task runs (Example: days)'),
    sa.CheckConstraint('every >= 1', name='celery_intervalschedule_every_check'),
    sa.PrimaryKeyConstraint('id', name='celery_intervalschedule_pkey')
    )
    op.create_table('celery_periodictask',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Short Description For This Task'),
    sa.Column('task', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='The Name of the Celery Task that Should be Run.  (Example: "proj.tasks.import_contacts")'),
    sa.Column('args', sa.TEXT(), autoincrement=False, nullable=False, comment='JSON encoded positional arguments (Example: ["arg1", "arg2"])'),
    sa.Column('kwargs', sa.TEXT(), autoincrement=False, nullable=False, comment='JSON encoded keyword arguments (Example: {"argument": "value"})'),
    sa.Column('queue', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Queue defined in CELERY_TASK_QUEUES. Leave None for default queuing.'),
    sa.Column('exchange', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Override Exchange for low-level AMQP routing'),
    sa.Column('routing_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Override Routing Key for low-level AMQP routing'),
    sa.Column('headers', sa.TEXT(), autoincrement=False, nullable=True, comment='JSON encoded message headers for the AMQP message.'),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True, comment='Priority Number between 0 and 255. Supported by: RabbitMQ, Redis (priority reversed, 0 is highest).'),
    sa.Column('expires', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Datetime after which the schedule will no longer trigger the task to run'),
    sa.Column('expire_seconds', sa.INTEGER(), autoincrement=False, nullable=True, comment='Timedelta with seconds which the schedule will no longer trigger the task to run'),
    sa.Column('one_off', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='If True, the schedule will only run the task a single time'),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Datetime when the schedule should begin triggering the task to run'),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Set to False to disable the schedule'),
    sa.Column('last_run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Datetime that the schedule last triggered the task to run. '),
    sa.Column('total_run_count', sa.INTEGER(), autoincrement=False, nullable=False, comment='Running count of how many times the schedule has triggered the task'),
    sa.Column('date_changed', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Datetime that this PeriodicTask was last modified'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Detailed description about the details of this Periodic Task'),
    sa.Column('discriminator', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='Lower case name of the schedule class. '),
    sa.Column('schedule_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='ID of the schedule model object. '),
    sa.CheckConstraint('priority >= 0 AND priority <= 255', name='celery_periodictask_priority_check'),
    sa.PrimaryKeyConstraint('id', name='celery_periodictask_pkey'),
    sa.UniqueConstraint('name', name='celery_periodictask_name_key')
    )
    # ### end Alembic commands ###
