"""add mas_odk_connections and map_project_odk

Revision ID: 93c5cf3f4109
Revises: c2d4e6f8a1b3
Create Date: 2026-03-10 03:47:38.892493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM as PgEnum


# revision identifiers, used by Alembic.
revision = '93c5cf3f4109'
down_revision = 'c2d4e6f8a1b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mas_odk_connections',
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('connection_name', sa.Text(), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('username_enc', sa.Text(), nullable=False),
    sa.Column('username_salt', sa.String(length=32), nullable=False),
    sa.Column('password_enc', sa.Text(), nullable=False),
    sa.Column('password_salt', sa.String(length=32), nullable=False),
    sa.Column('status', PgEnum('pending', 'active', 'deactive', name='status_enum', create_type=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('connection_id'),
    sa.UniqueConstraint('connection_name')
    )
    with op.batch_alter_table('mas_odk_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mas_odk_connections_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mas_odk_connections_status'), ['status'], unique=False)

    op.create_table('map_project_odk',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.String(length=6), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['mas_odk_connections.connection_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['va_project_master.project_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('map_project_odk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_map_project_odk_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_map_project_odk_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_map_project_odk_project_id'), ['project_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_project_odk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_map_project_odk_project_id'))
        batch_op.drop_index(batch_op.f('ix_map_project_odk_id'))
        batch_op.drop_index(batch_op.f('ix_map_project_odk_connection_id'))

    op.drop_table('map_project_odk')
    with op.batch_alter_table('mas_odk_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mas_odk_connections_status'))
        batch_op.drop_index(batch_op.f('ix_mas_odk_connections_connection_id'))

    op.drop_table('mas_odk_connections')
    # ### end Alembic commands ###
