"""new initial migration

Revision ID: a395774fa312
Revises: 
Create Date: 2025-08-06 22:28:26.600853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a395774fa312'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('va_icd_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=True),
    sa.Column('icd_code', sa.String(length=8), nullable=False),
    sa.Column('icd_to_display', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('va_icd_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_va_icd_codes_icd_code'), ['icd_code'], unique=False)

    op.create_table('va_research_projects',
    sa.Column('project_id', sa.String(length=6), nullable=False),
    sa.Column('project_code', sa.String(length=6), nullable=True),
    sa.Column('project_name', sa.Text(), nullable=False),
    sa.Column('project_nickname', sa.Text(), nullable=False),
    sa.Column('project_status', sa.Enum('pending', 'active', 'deactive', name='status_enum'), nullable=False),
    sa.Column('project_registered_at', sa.DateTime(), nullable=False),
    sa.Column('project_updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    with op.batch_alter_table('va_research_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_va_research_projects_project_id'), ['project_id'], unique=False)

    op.create_table('va_users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('vacode_language', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('vacode_formcount', sa.Integer(), nullable=False),
    sa.Column('permission', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('landing_page', sa.String(length=255), nullable=False),
    sa.Column('pw_reset_t_and_c', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('other', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_status', sa.Enum('pending', 'active', 'deactive', name='status_enum'), nullable=False),
    sa.Column('user_created_at', sa.DateTime(), nullable=False),
    sa.Column('user_updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('va_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_va_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_va_users_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_users_user_status'), ['user_status'], unique=False)

    op.create_table('va_sites',
    sa.Column('site_id', sa.String(length=4), nullable=False),
    sa.Column('project_id', sa.String(length=6), nullable=False),
    sa.Column('site_name', sa.Text(), nullable=False),
    sa.Column('site_abbr', sa.Text(), nullable=False),
    sa.Column('site_status', sa.Enum('pending', 'active', 'deactive', name='status_enum'), nullable=False),
    sa.Column('site_registered_at', sa.DateTime(), nullable=False),
    sa.Column('site_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['va_research_projects.project_id'], ),
    sa.PrimaryKeyConstraint('site_id')
    )
    with op.batch_alter_table('va_sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_va_sites_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_sites_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_sites_site_status'), ['site_status'], unique=False)

    op.create_table('va_forms',
    sa.Column('form_id', sa.String(length=12), nullable=False),
    sa.Column('project_id', sa.String(length=6), nullable=False),
    sa.Column('site_id', sa.String(length=4), nullable=False),
    sa.Column('odk_form_id', sa.String(length=64), nullable=False),
    sa.Column('odk_project_id', sa.String(length=2), nullable=False),
    sa.Column('form_type', sa.String(length=64), nullable=False),
    sa.Column('form_smartvahiv', sa.String(length=8), nullable=False),
    sa.Column('form_smartvamalaria', sa.String(length=8), nullable=False),
    sa.Column('form_smartvahce', sa.String(length=8), nullable=False),
    sa.Column('form_smartvafreetext', sa.String(length=8), nullable=False),
    sa.Column('form_smartvacountry', sa.String(length=4), nullable=False),
    sa.Column('form_status', sa.Enum('pending', 'active', 'deactive', name='status_enum'), nullable=False),
    sa.Column('form_registered_at', sa.DateTime(), nullable=False),
    sa.Column('form_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['va_research_projects.project_id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['va_sites.site_id'], ),
    sa.PrimaryKeyConstraint('form_id')
    )
    with op.batch_alter_table('va_forms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_va_forms_form_id'), ['form_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_forms_form_status'), ['form_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_forms_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_forms_site_id'), ['site_id'], unique=False)

    op.create_table('va_submissions',
    sa.Column('va_sid', sa.String(length=64), nullable=False),
    sa.Column('va_form_id', sa.String(length=12), nullable=False),
    sa.Column('va_submission_date', sa.DateTime(), nullable=True),
    sa.Column('va_odk_updatedat', sa.DateTime(), nullable=True),
    sa.Column('va_data_collector', sa.String(length=32), nullable=False),
    sa.Column('va_odk_reviewstate', sa.String(length=16), nullable=True),
    sa.Column('va_instance_name', sa.String(length=128), nullable=True),
    sa.Column('va_uniqueid_real', sa.String(length=128), nullable=True),
    sa.Column('va_uniqueid_masked', sa.String(length=128), nullable=False),
    sa.Column('va_consent', sa.String(length=4), nullable=False),
    sa.Column('va_narration_language', sa.String(length=16), nullable=False),
    sa.Column('va_deceased_age', sa.Integer(), nullable=False),
    sa.Column('va_deceased_gender', sa.String(length=8), nullable=False),
    sa.Column('va_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('va_summary', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('va_catcount', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('va_category_list', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('va_created_at', sa.DateTime(), nullable=False),
    sa.Column('va_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['va_form_id'], ['va_forms.form_id'], ),
    sa.PrimaryKeyConstraint('va_sid')
    )
    with op.batch_alter_table('va_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_va_submissions_va_consent'), ['va_consent'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_submissions_va_created_at'), ['va_created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_submissions_va_form_id'), ['va_form_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_submissions_va_narration_language'), ['va_narration_language'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_submissions_va_odk_reviewstate'), ['va_odk_reviewstate'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_submissions_va_odk_updatedat'), ['va_odk_updatedat'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_submissions_va_sid'), ['va_sid'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_submissions_va_submission_date'), ['va_submission_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_submissions_va_updated_at'), ['va_updated_at'], unique=False)

    op.create_table('va_allocations',
    sa.Column('va_allocation_id', sa.Uuid(), nullable=False),
    sa.Column('va_sid', sa.String(length=64), nullable=False),
    sa.Column('va_allocated_to', sa.Uuid(), nullable=False),
    sa.Column('va_allocation_for', sa.Enum('coding', 'reviewing', name='allocation_enum'), nullable=False),
    sa.Column('va_allocation_status', sa.Enum('pending', 'active', 'deactive', name='status_enum'), nullable=False),
    sa.Column('va_allocation_createdat', sa.DateTime(), nullable=False),
    sa.Column('va_allocation_updatedat', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['va_allocated_to'], ['va_users.user_id'], ),
    sa.ForeignKeyConstraint(['va_sid'], ['va_submissions.va_sid'], ),
    sa.PrimaryKeyConstraint('va_allocation_id')
    )
    with op.batch_alter_table('va_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_va_allocations_va_allocated_to'), ['va_allocated_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_allocations_va_allocation_createdat'), ['va_allocation_createdat'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_allocations_va_allocation_for'), ['va_allocation_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_allocations_va_allocation_id'), ['va_allocation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_allocations_va_allocation_status'), ['va_allocation_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_allocations_va_sid'), ['va_sid'], unique=False)

    op.create_table('va_coder_review',
    sa.Column('va_creview_id', sa.Uuid(), nullable=False),
    sa.Column('va_sid', sa.String(length=64), nullable=False),
    sa.Column('va_creview_by', sa.Uuid(), nullable=False),
    sa.Column('va_creview_reason', sa.String(length=32), nullable=False),
    sa.Column('va_creview_other', sa.Text(), nullable=True),
    sa.Column('va_creview_status', sa.Enum('pending', 'active', 'deactive', name='status_enum'), nullable=False),
    sa.Column('va_creview_createdat', sa.DateTime(), nullable=False),
    sa.Column('va_creview_updatedat', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['va_creview_by'], ['va_users.user_id'], ),
    sa.ForeignKeyConstraint(['va_sid'], ['va_submissions.va_sid'], ),
    sa.PrimaryKeyConstraint('va_creview_id')
    )
    with op.batch_alter_table('va_coder_review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_va_coder_review_va_creview_by'), ['va_creview_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_coder_review_va_creview_createdat'), ['va_creview_createdat'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_coder_review_va_creview_id'), ['va_creview_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_coder_review_va_creview_status'), ['va_creview_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_coder_review_va_sid'), ['va_sid'], unique=False)

    op.create_table('va_final_assessments',
    sa.Column('va_finassess_id', sa.Uuid(), nullable=False),
    sa.Column('va_sid', sa.String(length=64), nullable=False),
    sa.Column('va_finassess_by', sa.Uuid(), nullable=False),
    sa.Column('va_conclusive_cod', sa.Text(), nullable=False),
    sa.Column('va_finassess_remark', sa.Text(), nullable=True),
    sa.Column('va_finassess_status', sa.Enum('pending', 'active', 'deactive', name='status_enum'), nullable=False),
    sa.Column('va_finassess_createdat', sa.DateTime(), nullable=False),
    sa.Column('va_finassess_updatedat', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['va_finassess_by'], ['va_users.user_id'], ),
    sa.ForeignKeyConstraint(['va_sid'], ['va_submissions.va_sid'], ),
    sa.PrimaryKeyConstraint('va_finassess_id')
    )
    with op.batch_alter_table('va_final_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_va_final_assessments_va_finassess_by'), ['va_finassess_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_final_assessments_va_finassess_createdat'), ['va_finassess_createdat'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_final_assessments_va_finassess_id'), ['va_finassess_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_final_assessments_va_finassess_status'), ['va_finassess_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_final_assessments_va_sid'), ['va_sid'], unique=False)

    op.create_table('va_initial_assessments',
    sa.Column('va_iniassess_id', sa.Uuid(), nullable=False),
    sa.Column('va_sid', sa.String(length=64), nullable=False),
    sa.Column('va_iniassess_by', sa.Uuid(), nullable=False),
    sa.Column('va_immediate_cod', sa.Text(), nullable=False),
    sa.Column('va_antecedent_cod', sa.Text(), nullable=False),
    sa.Column('va_other_conditions', sa.Text(), nullable=True),
    sa.Column('va_iniassess_status', sa.Enum('pending', 'active', 'deactive', name='status_enum'), nullable=False),
    sa.Column('va_iniassess_createdat', sa.DateTime(), nullable=False),
    sa.Column('va_iniassess_updatedat', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['va_iniassess_by'], ['va_users.user_id'], ),
    sa.ForeignKeyConstraint(['va_sid'], ['va_submissions.va_sid'], ),
    sa.PrimaryKeyConstraint('va_iniassess_id')
    )
    with op.batch_alter_table('va_initial_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_va_initial_assessments_va_iniassess_by'), ['va_iniassess_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_initial_assessments_va_iniassess_createdat'), ['va_iniassess_createdat'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_initial_assessments_va_iniassess_id'), ['va_iniassess_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_initial_assessments_va_iniassess_status'), ['va_iniassess_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_initial_assessments_va_sid'), ['va_sid'], unique=False)

    op.create_table('va_reviewer_review',
    sa.Column('va_rreview_id', sa.Uuid(), nullable=False),
    sa.Column('va_sid', sa.String(length=64), nullable=False),
    sa.Column('va_rreview_by', sa.Uuid(), nullable=False),
    sa.Column('va_rreview_narrpos', sa.String(length=16), nullable=False),
    sa.Column('va_rreview_narrneg', sa.String(length=16), nullable=False),
    sa.Column('va_rreview_narrchrono', sa.String(length=32), nullable=False),
    sa.Column('va_rreview_narrdoc', sa.String(length=32), nullable=False),
    sa.Column('va_rreview_narrcomorb', sa.String(length=16), nullable=False),
    sa.Column('va_rreview', sa.String(length=16), nullable=False),
    sa.Column('va_rreview_fail', sa.Text(), nullable=True),
    sa.Column('va_rreview_remark', sa.Text(), nullable=True),
    sa.Column('va_rreview_status', sa.Enum('pending', 'active', 'deactive', name='status_enum'), nullable=False),
    sa.Column('va_rreview_createdat', sa.DateTime(), nullable=False),
    sa.Column('va_rreview_updatedat', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['va_rreview_by'], ['va_users.user_id'], ),
    sa.ForeignKeyConstraint(['va_sid'], ['va_submissions.va_sid'], ),
    sa.PrimaryKeyConstraint('va_rreview_id')
    )
    with op.batch_alter_table('va_reviewer_review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_va_reviewer_review_va_rreview'), ['va_rreview'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_reviewer_review_va_rreview_by'), ['va_rreview_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_reviewer_review_va_rreview_createdat'), ['va_rreview_createdat'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_reviewer_review_va_rreview_id'), ['va_rreview_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_reviewer_review_va_rreview_status'), ['va_rreview_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_reviewer_review_va_sid'), ['va_sid'], unique=False)

    op.create_table('va_smartva_results',
    sa.Column('va_smartva_id', sa.Uuid(), nullable=False),
    sa.Column('va_sid', sa.String(length=64), nullable=False),
    sa.Column('va_smartva_age', sa.String(length=8), nullable=True),
    sa.Column('va_smartva_gender', sa.String(length=8), nullable=True),
    sa.Column('va_smartva_cause1', sa.Text(), nullable=True),
    sa.Column('va_smartva_likelihood1', sa.String(length=32), nullable=True),
    sa.Column('va_smartva_keysymptom1', sa.Text(), nullable=True),
    sa.Column('va_smartva_cause2', sa.Text(), nullable=True),
    sa.Column('va_smartva_likelihood2', sa.String(length=32), nullable=True),
    sa.Column('va_smartva_keysymptom2', sa.Text(), nullable=True),
    sa.Column('va_smartva_cause3', sa.Text(), nullable=True),
    sa.Column('va_smartva_likelihood3', sa.String(length=32), nullable=True),
    sa.Column('va_smartva_keysymptom3', sa.Text(), nullable=True),
    sa.Column('va_smartva_allsymptoms', sa.Text(), nullable=True),
    sa.Column('va_smartva_resultfor', sa.String(length=16), nullable=True),
    sa.Column('va_smartva_cause1icd', sa.String(length=8), nullable=True),
    sa.Column('va_smartva_cause2icd', sa.String(length=8), nullable=True),
    sa.Column('va_smartva_cause3icd', sa.String(length=8), nullable=True),
    sa.Column('va_smartva_status', sa.Enum('pending', 'active', 'deactive', name='status_enum'), nullable=False),
    sa.Column('va_smartva_addedat', sa.DateTime(), nullable=False),
    sa.Column('va_smartva_updatedat', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['va_sid'], ['va_submissions.va_sid'], ),
    sa.PrimaryKeyConstraint('va_smartva_id')
    )
    with op.batch_alter_table('va_smartva_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_va_smartva_results_va_sid'), ['va_sid'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_smartva_results_va_smartva_addedat'), ['va_smartva_addedat'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_smartva_results_va_smartva_id'), ['va_smartva_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_smartva_results_va_smartva_status'), ['va_smartva_status'], unique=False)

    op.create_table('va_submissions_auditlog',
    sa.Column('va_audit_id', sa.Integer(), nullable=False),
    sa.Column('va_sid', sa.String(length=64), nullable=False),
    sa.Column('va_audit_byrole', sa.String(length=8), nullable=False),
    sa.Column('va_audit_by', sa.Uuid(), nullable=True),
    sa.Column('va_audit_operation', sa.String(length=1), nullable=False),
    sa.Column('va_audit_action', sa.String(length=128), nullable=False),
    sa.Column('va_audit_entityid', sa.Uuid(), nullable=True),
    sa.Column('va_audit_createdat', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['va_sid'], ['va_submissions.va_sid'], ),
    sa.PrimaryKeyConstraint('va_audit_id')
    )
    with op.batch_alter_table('va_submissions_auditlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_va_submissions_auditlog_va_sid'), ['va_sid'], unique=False)

    op.create_table('va_usernotes',
    sa.Column('note_id', sa.Uuid(), nullable=False),
    sa.Column('note_by', sa.Uuid(), nullable=False),
    sa.Column('note_recordedwhen', sa.Enum('coding', 'reviewing', 'viewing', name='usernote_enum'), nullable=False),
    sa.Column('note_vasubmission', sa.String(length=64), nullable=False),
    sa.Column('note_content', sa.Text(), nullable=True),
    sa.Column('note_status', sa.Enum('pending', 'active', 'deactive', name='status_enum'), nullable=False),
    sa.Column('note_added_at', sa.DateTime(), nullable=False),
    sa.Column('note_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['note_by'], ['va_users.user_id'], ),
    sa.ForeignKeyConstraint(['note_vasubmission'], ['va_submissions.va_sid'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    with op.batch_alter_table('va_usernotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_va_usernotes_note_added_at'), ['note_added_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_usernotes_note_by'), ['note_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_usernotes_note_id'), ['note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_usernotes_note_status'), ['note_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_va_usernotes_note_vasubmission'), ['note_vasubmission'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('va_usernotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_va_usernotes_note_vasubmission'))
        batch_op.drop_index(batch_op.f('ix_va_usernotes_note_status'))
        batch_op.drop_index(batch_op.f('ix_va_usernotes_note_id'))
        batch_op.drop_index(batch_op.f('ix_va_usernotes_note_by'))
        batch_op.drop_index(batch_op.f('ix_va_usernotes_note_added_at'))

    op.drop_table('va_usernotes')
    with op.batch_alter_table('va_submissions_auditlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_va_submissions_auditlog_va_sid'))

    op.drop_table('va_submissions_auditlog')
    with op.batch_alter_table('va_smartva_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_va_smartva_results_va_smartva_status'))
        batch_op.drop_index(batch_op.f('ix_va_smartva_results_va_smartva_id'))
        batch_op.drop_index(batch_op.f('ix_va_smartva_results_va_smartva_addedat'))
        batch_op.drop_index(batch_op.f('ix_va_smartva_results_va_sid'))

    op.drop_table('va_smartva_results')
    with op.batch_alter_table('va_reviewer_review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_va_reviewer_review_va_sid'))
        batch_op.drop_index(batch_op.f('ix_va_reviewer_review_va_rreview_status'))
        batch_op.drop_index(batch_op.f('ix_va_reviewer_review_va_rreview_id'))
        batch_op.drop_index(batch_op.f('ix_va_reviewer_review_va_rreview_createdat'))
        batch_op.drop_index(batch_op.f('ix_va_reviewer_review_va_rreview_by'))
        batch_op.drop_index(batch_op.f('ix_va_reviewer_review_va_rreview'))

    op.drop_table('va_reviewer_review')
    with op.batch_alter_table('va_initial_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_va_initial_assessments_va_sid'))
        batch_op.drop_index(batch_op.f('ix_va_initial_assessments_va_iniassess_status'))
        batch_op.drop_index(batch_op.f('ix_va_initial_assessments_va_iniassess_id'))
        batch_op.drop_index(batch_op.f('ix_va_initial_assessments_va_iniassess_createdat'))
        batch_op.drop_index(batch_op.f('ix_va_initial_assessments_va_iniassess_by'))

    op.drop_table('va_initial_assessments')
    with op.batch_alter_table('va_final_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_va_final_assessments_va_sid'))
        batch_op.drop_index(batch_op.f('ix_va_final_assessments_va_finassess_status'))
        batch_op.drop_index(batch_op.f('ix_va_final_assessments_va_finassess_id'))
        batch_op.drop_index(batch_op.f('ix_va_final_assessments_va_finassess_createdat'))
        batch_op.drop_index(batch_op.f('ix_va_final_assessments_va_finassess_by'))

    op.drop_table('va_final_assessments')
    with op.batch_alter_table('va_coder_review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_va_coder_review_va_sid'))
        batch_op.drop_index(batch_op.f('ix_va_coder_review_va_creview_status'))
        batch_op.drop_index(batch_op.f('ix_va_coder_review_va_creview_id'))
        batch_op.drop_index(batch_op.f('ix_va_coder_review_va_creview_createdat'))
        batch_op.drop_index(batch_op.f('ix_va_coder_review_va_creview_by'))

    op.drop_table('va_coder_review')
    with op.batch_alter_table('va_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_va_allocations_va_sid'))
        batch_op.drop_index(batch_op.f('ix_va_allocations_va_allocation_status'))
        batch_op.drop_index(batch_op.f('ix_va_allocations_va_allocation_id'))
        batch_op.drop_index(batch_op.f('ix_va_allocations_va_allocation_for'))
        batch_op.drop_index(batch_op.f('ix_va_allocations_va_allocation_createdat'))
        batch_op.drop_index(batch_op.f('ix_va_allocations_va_allocated_to'))

    op.drop_table('va_allocations')
    with op.batch_alter_table('va_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_va_submissions_va_updated_at'))
        batch_op.drop_index(batch_op.f('ix_va_submissions_va_submission_date'))
        batch_op.drop_index(batch_op.f('ix_va_submissions_va_sid'))
        batch_op.drop_index(batch_op.f('ix_va_submissions_va_odk_updatedat'))
        batch_op.drop_index(batch_op.f('ix_va_submissions_va_odk_reviewstate'))
        batch_op.drop_index(batch_op.f('ix_va_submissions_va_narration_language'))
        batch_op.drop_index(batch_op.f('ix_va_submissions_va_form_id'))
        batch_op.drop_index(batch_op.f('ix_va_submissions_va_created_at'))
        batch_op.drop_index(batch_op.f('ix_va_submissions_va_consent'))

    op.drop_table('va_submissions')
    with op.batch_alter_table('va_forms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_va_forms_site_id'))
        batch_op.drop_index(batch_op.f('ix_va_forms_project_id'))
        batch_op.drop_index(batch_op.f('ix_va_forms_form_status'))
        batch_op.drop_index(batch_op.f('ix_va_forms_form_id'))

    op.drop_table('va_forms')
    with op.batch_alter_table('va_sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_va_sites_site_status'))
        batch_op.drop_index(batch_op.f('ix_va_sites_site_id'))
        batch_op.drop_index(batch_op.f('ix_va_sites_project_id'))

    op.drop_table('va_sites')
    with op.batch_alter_table('va_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_va_users_user_status'))
        batch_op.drop_index(batch_op.f('ix_va_users_user_id'))
        batch_op.drop_index(batch_op.f('ix_va_users_email'))

    op.drop_table('va_users')
    with op.batch_alter_table('va_research_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_va_research_projects_project_id'))

    op.drop_table('va_research_projects')
    with op.batch_alter_table('va_icd_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_va_icd_codes_icd_code'))

    op.drop_table('va_icd_codes')
    # ### end Alembic commands ###
