"""add field mapping tables

Revision ID: f4928a94d422
Revises: 10604d1d150d
Create Date: 2026-03-10 10:40:20.107292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4928a94d422'
down_revision = '10604d1d150d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mas_form_types',
    sa.Column('form_type_id', sa.Uuid(), nullable=False),
    sa.Column('form_type_code', sa.String(length=32), nullable=False),
    sa.Column('form_type_name', sa.String(length=128), nullable=False),
    sa.Column('form_type_description', sa.Text(), nullable=True),
    sa.Column('base_template_path', sa.String(length=256), nullable=True),
    sa.Column('mapping_version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('form_type_id')
    )
    with op.batch_alter_table('mas_form_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mas_form_types_form_type_code'), ['form_type_code'], unique=True)

    op.create_table('mas_category_order',
    sa.Column('category_order_id', sa.Uuid(), nullable=False),
    sa.Column('form_type_id', sa.Uuid(), nullable=False),
    sa.Column('category_code', sa.String(length=64), nullable=False),
    sa.Column('category_name', sa.String(length=128), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['form_type_id'], ['mas_form_types.form_type_id'], ),
    sa.PrimaryKeyConstraint('category_order_id'),
    sa.UniqueConstraint('form_type_id', 'category_code', name='uq_category_form_type')
    )
    with op.batch_alter_table('mas_category_order', schema=None) as batch_op:
        batch_op.create_index('idx_mas_category_order_form_type', ['form_type_id'], unique=False)

    op.create_table('mas_choice_mappings',
    sa.Column('choice_id', sa.Uuid(), nullable=False),
    sa.Column('form_type_id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.String(length=64), nullable=False),
    sa.Column('choice_value', sa.String(length=128), nullable=False),
    sa.Column('choice_label', sa.String(length=256), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['form_type_id'], ['mas_form_types.form_type_id'], ),
    sa.PrimaryKeyConstraint('choice_id'),
    sa.UniqueConstraint('form_type_id', 'field_id', 'choice_value', name='uq_choice_form_type_field')
    )
    with op.batch_alter_table('mas_choice_mappings', schema=None) as batch_op:
        batch_op.create_index('idx_mas_choice_mappings_field', ['form_type_id', 'field_id'], unique=False)
        batch_op.create_index('idx_mas_choice_mappings_form_type', ['form_type_id'], unique=False)

    op.create_table('mas_field_display_config',
    sa.Column('config_id', sa.Uuid(), nullable=False),
    sa.Column('form_type_id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.String(length=64), nullable=False),
    sa.Column('category_code', sa.String(length=64), nullable=True),
    sa.Column('subcategory_code', sa.String(length=64), nullable=True),
    sa.Column('short_label', sa.String(length=256), nullable=True),
    sa.Column('full_label', sa.Text(), nullable=True),
    sa.Column('summary_label', sa.String(length=256), nullable=True),
    sa.Column('field_type', sa.String(length=32), nullable=True),
    sa.Column('age_group', sa.String(length=16), nullable=True),
    sa.Column('flip_color', sa.Boolean(), nullable=False),
    sa.Column('is_info', sa.Boolean(), nullable=False),
    sa.Column('summary_include', sa.Boolean(), nullable=False),
    sa.Column('is_pii', sa.Boolean(), nullable=False),
    sa.Column('pii_type', sa.String(length=32), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['form_type_id'], ['mas_form_types.form_type_id'], ),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('form_type_id', 'field_id', name='uq_field_config_form_type')
    )
    with op.batch_alter_table('mas_field_display_config', schema=None) as batch_op:
        batch_op.create_index('idx_mas_field_display_config_category', ['form_type_id', 'category_code'], unique=False)
        batch_op.create_index('idx_mas_field_display_config_form_type', ['form_type_id'], unique=False)

    op.create_table('mas_pii_access_log',
    sa.Column('log_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('form_type_id', sa.Uuid(), nullable=True),
    sa.Column('field_id', sa.String(length=64), nullable=False),
    sa.Column('submission_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['form_type_id'], ['mas_form_types.form_type_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('mas_pii_access_log', schema=None) as batch_op:
        batch_op.create_index('idx_mas_pii_access_log_timestamp', ['accessed_at'], unique=False)
        batch_op.create_index('idx_mas_pii_access_log_user', ['user_id'], unique=False)

    op.create_table('mas_subcategory_order',
    sa.Column('subcategory_order_id', sa.Uuid(), nullable=False),
    sa.Column('form_type_id', sa.Uuid(), nullable=False),
    sa.Column('category_code', sa.String(length=64), nullable=False),
    sa.Column('subcategory_code', sa.String(length=64), nullable=False),
    sa.Column('subcategory_name', sa.String(length=128), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['form_type_id'], ['mas_form_types.form_type_id'], ),
    sa.PrimaryKeyConstraint('subcategory_order_id'),
    sa.UniqueConstraint('form_type_id', 'category_code', 'subcategory_code', name='uq_subcategory_form_type')
    )
    with op.batch_alter_table('mas_subcategory_order', schema=None) as batch_op:
        batch_op.create_index('idx_mas_subcategory_order_form_type', ['form_type_id'], unique=False)

    # Add form_type_id to va_forms (nullable - will be populated in Phase 2)
    op.add_column('va_forms',
        sa.Column('form_type_id', sa.Uuid(), sa.ForeignKey('mas_form_types.form_type_id'), nullable=True)
    )
    op.create_index('idx_va_forms_form_type', 'va_forms', ['form_type_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mas_subcategory_order', schema=None) as batch_op:
        batch_op.drop_index('idx_mas_subcategory_order_form_type')

    op.drop_table('mas_subcategory_order')
    with op.batch_alter_table('mas_pii_access_log', schema=None) as batch_op:
        batch_op.drop_index('idx_mas_pii_access_log_user')
        batch_op.drop_index('idx_mas_pii_access_log_timestamp')

    op.drop_table('mas_pii_access_log')
    with op.batch_alter_table('mas_field_display_config', schema=None) as batch_op:
        batch_op.drop_index('idx_mas_field_display_config_form_type')
        batch_op.drop_index('idx_mas_field_display_config_category')

    op.drop_table('mas_field_display_config')
    with op.batch_alter_table('mas_choice_mappings', schema=None) as batch_op:
        batch_op.drop_index('idx_mas_choice_mappings_form_type')
        batch_op.drop_index('idx_mas_choice_mappings_field')

    op.drop_table('mas_choice_mappings')
    with op.batch_alter_table('mas_category_order', schema=None) as batch_op:
        batch_op.drop_index('idx_mas_category_order_form_type')

    op.drop_table('mas_category_order')
    with op.batch_alter_table('mas_form_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mas_form_types_form_type_code'))

    op.drop_table('mas_form_types')

    # Remove form_type_id from va_forms
    op.drop_index('idx_va_forms_form_type', 'va_forms')
    op.drop_column('va_forms', 'form_type_id')
    # ### end Alembic commands ###
