"""Generate app/static/js/codedit_messages.js from WHO's CoDEdit message page.

The local CoDEdit engine returns back-end issues (BER-CE-n) as a bare key
such as RE_W_IV_CodeURIMismatch; WHO publishes the sentence for each ID on
WHO's page, kept as docs/kb/DORIS/who-codedit-report-message-identifiers.md.
Run: python scripts/generate_codedit_messages.py
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs/kb/DORIS/who-codedit-report-message-identifiers.md"
TARGET = ROOT / "app/static/js/codedit_messages.js"


def messages(page: str) -> dict[str, str]:
    # Definition rows are "| BER-CE-n | sentence |"; index rows list several
    # IDs in their second cell and are skipped by the pattern.
    rows = re.findall(r"^\| (BER-CE-\d+) \| (.+?) \|\s*$", page, flags=re.M)
    return {key: body.strip() for key, body in rows}


if __name__ == "__main__":
    table = messages(SOURCE.read_text(encoding="utf-8"))
    TARGET.write_text(
        "// Generated by scripts/generate_codedit_messages.py from WHO's CoDEdit\n"
        "// message page; do not edit by hand.\n"
        f"export var codeditMessages = {json.dumps(table, indent=2, sort_keys=True)};\n",
        encoding="utf-8",
    )
    print(f"{len(table)} messages -> {TARGET.relative_to(ROOT)}")
