"""Generate app/static/js/codedit_messages.js from WHO's CoDEdit message page.

The local CoDEdit engine returns back-end issues (BER-CE-n) as a bare key
such as RE_W_IV_CodeURIMismatch; WHO publishes the sentence for each ID on
the saved page docs/kb/DORIS/CODEDIT Report Message Identifiers - ICD-API
Homepage.html. Run: python scripts/generate_codedit_messages.py
"""

import html
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs/kb/DORIS/CODEDIT Report Message Identifiers - ICD-API Homepage.html"
TARGET = ROOT / "app/static/js/codedit_messages.js"


def messages(page: str) -> dict[str, str]:
    text = re.sub(r"<script.*?</script>|<style.*?</style>", "", page, flags=re.S)
    text = re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", " ", text)))
    parts = re.split(r"\b(BER-CE-\d+)\b", text)
    found = {}
    for key, body in zip(parts[1::2], parts[2::2]):
        body = body.strip(" ,")
        # Keep definitions; skip index lists ("BER-CE-8, BER-CE-9 ...") and the
        # generic "Back-end CoDEdit rule with identifier n" line.
        body = re.split(r" (?=BER-CE-|FER-CE-|Front-End|> Note)", body)[0].strip()
        if len(body) > 40 and not body.startswith("Back-end"):
            found.setdefault(key, body)
    return found


if __name__ == "__main__":
    table = messages(SOURCE.read_text(encoding="utf-8", errors="ignore"))
    TARGET.write_text(
        "// Generated by scripts/generate_codedit_messages.py from WHO's CoDEdit\n"
        "// message page; do not edit by hand.\n"
        f"export var codeditMessages = {json.dumps(table, indent=2, sort_keys=True)};\n",
        encoding="utf-8",
    )
    print(f"{len(table)} messages -> {TARGET.relative_to(ROOT)}")
